-- Schema inicial — SQL portável (H2 MODE=PostgreSQL / PostgreSQL)

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    tipo VARCHAR(20) NOT NULL
);

CREATE TABLE forma_pagamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    CONSTRAINT fk_forma_pagamento_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE INDEX idx_forma_pagamento_usuario_id ON forma_pagamento (usuario_id);

CREATE TABLE cartao_credito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forma_pagamento_id BIGINT NOT NULL,
    dia_fechamento INT NOT NULL,
    dia_vencimento INT NOT NULL,
    limite NUMERIC(19, 2),
    CONSTRAINT uk_cartao_credito_forma_pagamento UNIQUE (forma_pagamento_id),
    CONSTRAINT fk_cartao_credito_forma_pagamento FOREIGN KEY (forma_pagamento_id) REFERENCES forma_pagamento (id)
);

CREATE TABLE fatura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cartao_credito_id BIGINT NOT NULL,
    mes_referencia VARCHAR(7) NOT NULL,
    data_fechamento DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT uk_fatura_cartao_mes_referencia UNIQUE (cartao_credito_id, mes_referencia),
    CONSTRAINT fk_fatura_cartao_credito FOREIGN KEY (cartao_credito_id) REFERENCES cartao_credito (id)
);

CREATE INDEX idx_fatura_cartao_credito_id ON fatura (cartao_credito_id);

CREATE TABLE compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    categoria_id BIGINT NOT NULL,
    forma_pagamento_id BIGINT NOT NULL,
    descricao VARCHAR(500) NOT NULL,
    valor_total NUMERIC(19, 2) NOT NULL,
    data_compra DATE NOT NULL,
    num_parcelas INT NOT NULL DEFAULT 1,
    CONSTRAINT fk_compra_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT fk_compra_categoria FOREIGN KEY (categoria_id) REFERENCES categoria (id),
    CONSTRAINT fk_compra_forma_pagamento FOREIGN KEY (forma_pagamento_id) REFERENCES forma_pagamento (id)
);

CREATE INDEX idx_compra_usuario_id ON compra (usuario_id);
CREATE INDEX idx_compra_data_compra ON compra (data_compra);

CREATE TABLE parcela (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id BIGINT NOT NULL,
    numero_parcela INT NOT NULL,
    valor_parcela NUMERIC(19, 2) NOT NULL,
    fatura_id BIGINT,
    data_vencimento DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_parcela_compra FOREIGN KEY (compra_id) REFERENCES compra (id),
    CONSTRAINT fk_parcela_fatura FOREIGN KEY (fatura_id) REFERENCES fatura (id)
);

CREATE INDEX idx_parcela_fatura_id ON parcela (fatura_id);
CREATE INDEX idx_parcela_data_vencimento ON parcela (data_vencimento);
