-- Gastos fixos/recorrentes e vínculo opcional em compra

CREATE TABLE gasto_fixo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    categoria_id BIGINT NOT NULL,
    forma_pagamento_id BIGINT NOT NULL,
    descricao VARCHAR(500) NOT NULL,
    valor_previsto NUMERIC(19, 2) NOT NULL,
    dia_vencimento INT NOT NULL,
    recorrencia VARCHAR(20) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_gasto_fixo_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT fk_gasto_fixo_categoria FOREIGN KEY (categoria_id) REFERENCES categoria (id),
    CONSTRAINT fk_gasto_fixo_forma_pagamento FOREIGN KEY (forma_pagamento_id) REFERENCES forma_pagamento (id)
);

CREATE INDEX idx_gasto_fixo_usuario_id ON gasto_fixo (usuario_id);

ALTER TABLE compra ADD COLUMN gasto_fixo_id BIGINT;

ALTER TABLE compra ADD CONSTRAINT fk_compra_gasto_fixo FOREIGN KEY (gasto_fixo_id) REFERENCES gasto_fixo (id);

CREATE INDEX idx_compra_gasto_fixo_id ON compra (gasto_fixo_id);
